version: 1.0.{build}

image: Visual Studio 2015

configuration:
  - Debug

clone_depth: 1

clone_folder: C:\projects\ponyc

install:
  - ps: |
      cd C:\
      $premakeInstalled = Test-Path C:\premake5.exe
      $llvmInstalled = Test-Path C:\LLVM
      if(-Not $premakeInstalled)
      {
        wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha8/premake-5.0.0-alpha8-windows.zip -OutFile C:\premake5.zip
        7z x C:\premake5.zip
        del C:\premake5.zip
      }
      if(-Not $llvmInstalled)
      {
        wget http://llvm.org/releases/3.8.0/LLVM-3.8.0-win64.exe -OutFile C:\llvm38.exe
        dir C:\
#        Start-Process -Wait C:\llvm38.exe /S /D:=C:\LLVM\
        dir C:\
      }
      $env:path += ";C:\LLVM\bin"
  - start "" /wait C:\llvm38.exe /S /D:=C:\LLVM\
  - dir C:\

cache:
  - C:\LLVM\ -> .appveyor.yml
  - C:\premake5.exe -> .appveyor.yml

before_build:
  - rmdir /s /q C:\projects\ponyc
  - git clone -q --depth=1 --branch=master https://github.com/dipinhora/ponyc.git C:\projects\ponyc
  - ps: cd C:\projects\ponyc
  - C:\premake5.exe --with-tests --to=work/vs2015 vs2015

build:
  project: work\vs2015\ponyc.sln
  verbosity: minimal

test_script:
#  - CALL "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\amd64\\vcvars64.bat"
#  - CALL "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\bin\\vcvars32.bat"
  - C:\projects\ponyc\build\debug\testc.exe
  - C:\projects\ponyc\build\debug\testrt.exe
  - C:\projects\ponyc\build\debug\ponyc.exe -V 3 -o C:\projects\ponyc\ -d -s packages/stdlib
  - echo %CD%
  - dir
  - stdlib.exe
  - del stdlib.exe

