language: c

sudo: required

branches:
  only:
    - /^ponyc-nightly-.*$/

addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - llvm-3.8
      - llvm-3.8-dev
      - ruby-dev
      - build-essential
      - rpm

matrix:
  include:
    - os: linux
      env:
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug
    - os: osx
      env:
        - LLVM_CONFIG="llvm-config-3.8"
        - config=debug

install:
  - if [[ $TRAVIS_OS_NAME = "linux" && $TRAVIS_TAG != "" ]];
    then
      gem install fpm;
      export CC="gcc-4.9";
      export CXX="g++-4.9";
      wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.21.tar.bz2;
      tar -xjvf pcre2-10.21.tar.bz2;
      cd pcre2-10.21 && ./configure --prefix=/usr && make && sudo make install;
      cd -;
    fi;
  - if [[ $TRAVIS_OS_NAME = "osx" && $TRAVIS_TAG != "" ]];
    then
      brew update;
      brew install llvm38 pcre2 libressl;
    fi;

script:
  - git clone https://github.com/dipinhora/ponyc.git
  - cd ponyc
  - if [[ $TRAVIS_OS_NAME = "linux" && $TRAVIS_TAG != "" ]];
    then
      make deploy nightly=true;
      export UPLOAD=yes;
    fi;

before_deploy:
  - export RELEASE_PKG_FILE=$(ls build/$config/bin/*)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RiaF7vjNb2zbdy1iVsvO9llR8ZPh1u4DjVWEv3OW+wJnaNqcMX3x+dAgaZ9NTDSBJMifquM+JR5SWSVoSc4Fq0+USFMSaLZ3cWofv1ZHt7p21VJ35l2y8dQgXUFL1GodensZVhdDBiZCWwrVIfSAGycsGatZNe3O6FEJeZ1erzw2EsW5UBJWNShTP+gqzRG+HJIbZ397q1kDXiKcIHv8oFzYCAp7rHokLKuTRJSxxGjXKfzk6uMZL9yiXuzOPdM7/M9iyQCOvFKmb2FSY1w71YT97/EGpawui4NMU7fh/rOpjZljWEK4Uc/02Zt1nOGcoa+6Q/dyHKvTP2aI6FJyGlrtlucCw80TK2JIfe5hKyYM2FcEaCybXfPWLdGQZ5o4ObrXoSlzbOfzL0Cm0JrHWGadxSg0R18Dwbm2NBSzwvtXXBB4UGuZZxezZalu5Y/DrK/a8Zu+J0nnX/4EVB6ArPmS+ebqW5KrAhBVLfu9osGBzqopflw7FsqP1GT21tqlWe9/1isamVWi91gh/aCzNEelmFSCODBzf12++E+rMNYU11dpcxZxIA68EDPHyxRmyglBokg9L8+0ec/B4spVsPBn7OkyiPZMYITlsQ7UqpFqVISVFLOUNSc80xCT2dEj9hh0hCfbGSbH9Y7Df8KLOUuPW8KNJkrCc1kpkEhJvLE=
  file_glob: true
  file: "build/$config/bin/*"
  on:
    tags: true
    condition: $UPLOAD = yes

